function Vout = ENpd(RPAValues,RPBValues,RPCValues,pValues,VssNValues)
Vs_s_0 = VssNValues(:,1);
Vs_s_1 = VssNValues(:,2);
Vs_s_2 = VssNValues(:,3);
Vs_s_3 = VssNValues(:,4);
PAx = RPAValues(:,1);
PAy = RPAValues(:,2);
PAz = RPAValues(:,3);
PCx = RPCValues(:,1);
PCy = RPCValues(:,2);
PCz = RPCValues(:,3);
PBx = RPBValues(:,1);
PBy = RPBValues(:,2);
PBz = RPBValues(:,3);
oo2p = 0.5./pValues;
ABx = PBx(1)-PAx(1);
ABy = PBy(1)-PAy(1);
ABz = PBz(1)-PAz(1);
%[p|VeN|s](0)
Vpx_s_0 = PAx.*Vs_s_0 - PCx.*Vs_s_1;
Vpy_s_0 = PAy.*Vs_s_0 - PCy.*Vs_s_1;
Vpz_s_0 = PAz.*Vs_s_0 - PCz.*Vs_s_1;
%[p|VeN|s](1)
Vpx_s_1 = PAx.*Vs_s_1 - PCx.*Vs_s_2;
Vpy_s_1 = PAy.*Vs_s_1 - PCy.*Vs_s_2;
Vpz_s_1 = PAz.*Vs_s_1 - PCz.*Vs_s_2;
%[p|VeN|s](2)
Vpx_s_2 = PAx.*Vs_s_2 - PCx.*Vs_s_3;
Vpy_s_2 = PAy.*Vs_s_2 - PCy.*Vs_s_3;
Vpz_s_2 = PAz.*Vs_s_2 - PCz.*Vs_s_3;
%Contracted (p|VeN|s)
Vpx_s = sum(Vpx_s_0);
Vpy_s = sum(Vpy_s_0);
Vpz_s = sum(Vpz_s_0);
%[d|VeN|s](0)
Vdxx_s_0 = PAx.*Vpx_s_0 - PCx.*Vpx_s_1 + 1.*oo2p.*(Vs_s_0 - Vs_s_1);
Vdxy_s_0 = PAx.*Vpy_s_0 - PCx.*Vpy_s_1;
Vdxz_s_0 = PAx.*Vpz_s_0 - PCx.*Vpz_s_1;
Vdyy_s_0 = PAy.*Vpy_s_0 - PCy.*Vpy_s_1 + 1.*oo2p.*(Vs_s_0 - Vs_s_1);
Vdyz_s_0 = PAy.*Vpz_s_0 - PCy.*Vpz_s_1;
Vdzz_s_0 = PAz.*Vpz_s_0 - PCz.*Vpz_s_1 + 1.*oo2p.*(Vs_s_0 - Vs_s_1);
%[d|VeN|s](1)
Vdxx_s_1 = PAx.*Vpx_s_1 - PCx.*Vpx_s_2 + 1.*oo2p.*(Vs_s_1 - Vs_s_2);
Vdxy_s_1 = PAx.*Vpy_s_1 - PCx.*Vpy_s_2;
Vdxz_s_1 = PAx.*Vpz_s_1 - PCx.*Vpz_s_2;
Vdyy_s_1 = PAy.*Vpy_s_1 - PCy.*Vpy_s_2 + 1.*oo2p.*(Vs_s_1 - Vs_s_2);
Vdyz_s_1 = PAy.*Vpz_s_1 - PCy.*Vpz_s_2;
Vdzz_s_1 = PAz.*Vpz_s_1 - PCz.*Vpz_s_2 + 1.*oo2p.*(Vs_s_1 - Vs_s_2);
%Contracted (d|VeN|s)
Vdxx_s = sum(Vdxx_s_0);
Vdxy_s = sum(Vdxy_s_0);
Vdxz_s = sum(Vdxz_s_0);
Vdyy_s = sum(Vdyy_s_0);
Vdyz_s = sum(Vdyz_s_0);
Vdzz_s = sum(Vdzz_s_0);
%[f|VeN|s](0)
Vfxxx_s_0 = PAx.*Vdxx_s_0 - PCx.*Vdxx_s_1 + 2.*oo2p.*(Vpx_s_0 - Vpx_s_1);
Vfxxy_s_0 = PAy.*Vdxx_s_0 - PCy.*Vdxx_s_1;
Vfxxz_s_0 = PAz.*Vdxx_s_0 - PCz.*Vdxx_s_1;
Vfxyy_s_0 = PAx.*Vdyy_s_0 - PCx.*Vdyy_s_1;
Vfxyz_s_0 = PAx.*Vdyz_s_0 - PCx.*Vdyz_s_1;
Vfxzz_s_0 = PAx.*Vdzz_s_0 - PCx.*Vdzz_s_1;
Vfyyy_s_0 = PAy.*Vdyy_s_0 - PCy.*Vdyy_s_1 + 2.*oo2p.*(Vpy_s_0 - Vpy_s_1);
Vfyyz_s_0 = PAz.*Vdyy_s_0 - PCz.*Vdyy_s_1;
Vfyzz_s_0 = PAy.*Vdzz_s_0 - PCy.*Vdzz_s_1;
Vfzzz_s_0 = PAz.*Vdzz_s_0 - PCz.*Vdzz_s_1 + 2.*oo2p.*(Vpz_s_0 - Vpz_s_1);
%Contracted (f|VeN|s)
Vfxxx_s = sum(Vfxxx_s_0);
Vfxxy_s = sum(Vfxxy_s_0);
Vfxxz_s = sum(Vfxxz_s_0);
Vfxyy_s = sum(Vfxyy_s_0);
Vfxyz_s = sum(Vfxyz_s_0);
Vfxzz_s = sum(Vfxzz_s_0);
Vfyyy_s = sum(Vfyyy_s_0);
Vfyyz_s = sum(Vfyyz_s_0);
Vfyzz_s = sum(Vfyzz_s_0);
Vfzzz_s = sum(Vfzzz_s_0);
%[p|VeN|p](0)
Vpx_px = ABx*Vpx_s + Vdxx_s;
Vpx_py = ABy*Vpx_s + Vdxy_s;
Vpx_pz = ABz*Vpx_s + Vdxz_s;
Vpy_px = ABx*Vpy_s + Vdxy_s;
Vpy_py = ABy*Vpy_s + Vdyy_s;
Vpy_pz = ABz*Vpy_s + Vdyz_s;
Vpz_px = ABx*Vpz_s + Vdxz_s;
Vpz_py = ABy*Vpz_s + Vdyz_s;
Vpz_pz = ABz*Vpz_s + Vdzz_s;
%[d|VeN|p](0)
Vdxx_px = ABx*Vdxx_s + Vfxxx_s;
Vdxx_py = ABy*Vdxx_s + Vfxxy_s;
Vdxx_pz = ABz*Vdxx_s + Vfxxz_s;
Vdxy_px = ABx*Vdxy_s + Vfxxy_s;
Vdxy_py = ABy*Vdxy_s + Vfxyy_s;
Vdxy_pz = ABz*Vdxy_s + Vfxyz_s;
Vdxz_px = ABx*Vdxz_s + Vfxxz_s;
Vdxz_py = ABy*Vdxz_s + Vfxyz_s;
Vdxz_pz = ABz*Vdxz_s + Vfxzz_s;
Vdyy_px = ABx*Vdyy_s + Vfxyy_s;
Vdyy_py = ABy*Vdyy_s + Vfyyy_s;
Vdyy_pz = ABz*Vdyy_s + Vfyyz_s;
Vdyz_px = ABx*Vdyz_s + Vfxyz_s;
Vdyz_py = ABy*Vdyz_s + Vfyyz_s;
Vdyz_pz = ABz*Vdyz_s + Vfyzz_s;
Vdzz_px = ABx*Vdzz_s + Vfxzz_s;
Vdzz_py = ABy*Vdzz_s + Vfyzz_s;
Vdzz_pz = ABz*Vdzz_s + Vfzzz_s;
%[p|VeN|d](0)
Vpx_dxx = ABx*Vpx_px + Vdxx_px;
Vpx_dxy = ABx*Vpx_py + Vdxx_py;
Vpx_dxz = ABx*Vpx_pz + Vdxx_pz;
Vpx_dyy = ABy*Vpx_py + Vdxy_py;
Vpx_dyz = ABy*Vpx_pz + Vdxy_pz;
Vpx_dzz = ABz*Vpx_pz + Vdxz_pz;
Vpy_dxx = ABx*Vpy_px + Vdxy_px;
Vpy_dxy = ABx*Vpy_py + Vdxy_py;
Vpy_dxz = ABx*Vpy_pz + Vdxy_pz;
Vpy_dyy = ABy*Vpy_py + Vdyy_py;
Vpy_dyz = ABy*Vpy_pz + Vdyy_pz;
Vpy_dzz = ABz*Vpy_pz + Vdyz_pz;
Vpz_dxx = ABx*Vpz_px + Vdxz_px;
Vpz_dxy = ABx*Vpz_py + Vdxz_py;
Vpz_dxz = ABx*Vpz_pz + Vdxz_pz;
Vpz_dyy = ABy*Vpz_py + Vdyz_py;
Vpz_dyz = ABy*Vpz_pz + Vdyz_pz;
Vpz_dzz = ABz*Vpz_pz + Vdzz_pz;
V = zeros(3,6);
V(1,1) = 1/1.73205080756888*Vpx_dxx;
V(1,2) = Vpx_dxy;
V(1,3) = Vpx_dxz;
V(1,4) = 1/1.73205080756888*Vpx_dyy;
V(1,5) = Vpx_dyz;
V(1,6) = 1/1.73205080756888*Vpx_dzz;
V(2,1) = 1/1.73205080756888*Vpy_dxx;
V(2,2) = Vpy_dxy;
V(2,3) = Vpy_dxz;
V(2,4) = 1/1.73205080756888*Vpy_dyy;
V(2,5) = Vpy_dyz;
V(2,6) = 1/1.73205080756888*Vpy_dzz;
V(3,1) = 1/1.73205080756888*Vpz_dxx;
V(3,2) = Vpz_dxy;
V(3,3) = Vpz_dxz;
V(3,4) = 1/1.73205080756888*Vpz_dyy;
V(3,5) = Vpz_dyz;
V(3,6) = 1/1.73205080756888*Vpz_dzz;
Vout = V;end
