function Vout = ENss(RPAValues,RPBValues,RPCValues,pValues,VssNValues)
Vs_s_0 = VssNValues(:,1);
PAx = RPAValues(:,1);
PAy = RPAValues(:,2);
PAz = RPAValues(:,3);
PCx = RPCValues(:,1);
PCy = RPCValues(:,2);
PCz = RPCValues(:,3);
PBx = RPBValues(:,1);
PBy = RPBValues(:,2);
PBz = RPBValues(:,3);
oo2p = 0.5./pValues;
ABx = PBx(1)-PAx(1);
ABy = PBy(1)-PAy(1);
ABz = PBz(1)-PAz(1);
V = zeros(1,1);
V(1,1) = sum(Vs_s_0);
Vout = V;end
