function gout = OSpssp(RPAValues,RPBValues,RQCValues,RQDValues,RWPValues,RWQValues,pValues,qValues,ppqValues,gSSSSNValues)
s_s_s_s_0 = gSSSSNValues(:,1);
s_s_s_s_1 = gSSSSNValues(:,2);
s_s_s_s_2 = gSSSSNValues(:,3);
PAx = RPAValues(:,1);
PAy = RPAValues(:,2);
PAz = RPAValues(:,3);
PBx = RPBValues(:,1);
PBy = RPBValues(:,2);
PBz = RPBValues(:,3);
QCx = RQCValues(:,1);
QCy = RQCValues(:,2);
QCz = RQCValues(:,3);
QDx = RQDValues(:,1);
QDy = RQDValues(:,2);
QDz = RQDValues(:,3);
WPx = RWPValues(:,1);
WPy = RWPValues(:,2);
WPz = RWPValues(:,3);
WQx = RWQValues(:,1);
WQy = RWQValues(:,2);
WQz = RWQValues(:,3);
ABx = PBx(1)-PAx(1);
ABy = PBy(1)-PAy(1);
ABz = PBz(1)-PAz(1);
CDx = QDx(1)-QCx(1);
CDy = QDy(1)-QCy(1);
CDz = QDz(1)-QCz(1);
oo2p = 0.5./pValues;
oo2q = 0.5./qValues;
qoppq = qValues./ppqValues;
oo2pq = 0.5./ppqValues;
%[ps|ss](0)
px_s_s_s_0 = PAx.*s_s_s_s_0 + WPx.*s_s_s_s_1;
py_s_s_s_0 = PAy.*s_s_s_s_0 + WPy.*s_s_s_s_1;
pz_s_s_s_0 = PAz.*s_s_s_s_0 + WPz.*s_s_s_s_1;
%[ps|ss](1)
px_s_s_s_1 = PAx.*s_s_s_s_1 + WPx.*s_s_s_s_2;
py_s_s_s_1 = PAy.*s_s_s_s_1 + WPy.*s_s_s_s_2;
pz_s_s_s_1 = PAz.*s_s_s_s_1 + WPz.*s_s_s_s_2;
%Contracted (ps|ss)
px_s_s_s = sum(px_s_s_s_0);
py_s_s_s = sum(py_s_s_s_0);
pz_s_s_s = sum(pz_s_s_s_0);
%[ps|ps](0)
px_s_px_s_0 = QCx.*px_s_s_s_0 + WQx.*px_s_s_s_1;
px_s_py_s_0 = QCy.*px_s_s_s_0 + WQy.*px_s_s_s_1;
px_s_pz_s_0 = QCz.*px_s_s_s_0 + WQz.*px_s_s_s_1;
py_s_px_s_0 = QCx.*py_s_s_s_0 + WQx.*py_s_s_s_1;
py_s_py_s_0 = QCy.*py_s_s_s_0 + WQy.*py_s_s_s_1;
py_s_pz_s_0 = QCz.*py_s_s_s_0 + WQz.*py_s_s_s_1;
pz_s_px_s_0 = QCx.*pz_s_s_s_0 + WQx.*pz_s_s_s_1;
pz_s_py_s_0 = QCy.*pz_s_s_s_0 + WQy.*pz_s_s_s_1;
pz_s_pz_s_0 = QCz.*pz_s_s_s_0 + WQz.*pz_s_s_s_1;
%Contracted (ps|ps)
px_s_px_s = sum(px_s_px_s_0);
px_s_py_s = sum(px_s_py_s_0);
px_s_pz_s = sum(px_s_pz_s_0);
py_s_px_s = sum(py_s_px_s_0);
py_s_py_s = sum(py_s_py_s_0);
py_s_pz_s = sum(py_s_pz_s_0);
pz_s_px_s = sum(pz_s_px_s_0);
pz_s_py_s = sum(pz_s_py_s_0);
pz_s_pz_s = sum(pz_s_pz_s_0);
gout = zeros(3,1,1,3);
gout(1,1,1,1) = px_s_s_px;
gout(1,1,1,2) = px_s_s_py;
gout(1,1,1,3) = px_s_s_pz;
gout(2,1,1,1) = py_s_s_px;
gout(2,1,1,2) = py_s_s_py;
gout(2,1,1,3) = py_s_s_pz;
gout(3,1,1,1) = pz_s_s_px;
gout(3,1,1,2) = pz_s_s_py;
gout(3,1,1,3) = pz_s_s_pz;
end